import Head from 'next/head'
import { Button, Flex } from 'rebass'
import { useState } from 'react'

import styled from 'styled-components'

const Container = styled.div`
  background-color: transparent;
  width: 325px;
  height: 204px;
  perspective: 1000px;
  animation-duration: 3s;
  animation-timing-function: ease-in-out;
  animation-iteration-count: infinite;
  overflow: hidden;
  transform: ${({ rotate }) => `rotateY(${rotate}deg)`};
`

const Content = styled.div`
  position: relative;
  width: 100%;
  height: 100%;
  text-align: center;

  transform: ${({ rotateContent }) => `rotateY(${rotateContent}deg)`};

  background-size: 100% 100%;
  border-radius: 5px;
  transition: transform 4s;
  transform-style: preserve-3d;
  :before {
    background-color: ${({ borderColor }) => borderColor || '#000000'};
    position: absolute;
    width: 100%;
    height: 100%;
    border-radius: 5px;
    overflow: hidden;
    z-index: 1;
    content: '';
    top: 0;
    left: 0;
    transform: rotateY(180deg) translateZ(1px);
    background-image: -webkit-linear-gradient(hsla(0, 0%, 100%, 0.25), hsla(0, 0%, 0%, 0.25));
  }
  :after {
    background-color: ${({ borderColor }) => borderColor || '#000000'};
    position: absolute;
    width: 100%;
    height: 100%;
    border-radius: 5px;
    overflow: hidden;
    z-index: 1;
    content: '';
    top: 0;
    left: 0;
    transform: rotateY(180deg) translateZ(5px);
    background-image: -webkit-linear-gradient(hsla(0, 0%, 100%, 0.25), hsla(0, 0%, 0%, 0.25));
  }
`

const Card = styled.div`
  background-color: #000000;
  position: absolute;
  width: 100%;
  height: 100%;
  border-radius: 5px;
  overflow: hidden;
  z-index: 1;
`

const FrontWrapper = styled(Card)`
  background-color: #000000;
  background-image: -webkit-linear-gradient(hsla(0, 0%, 100%, 0.25), hsla(0, 0%, 0%, 0.25));
  color: black;
  opacity: 1;
  transition: opacity 0 0.3s;
`

const BackWrapper = styled(Card)`
  background-color: #000000;
  color: white;
  transform: rotateY(180deg) translateZ(6px);
`

const Context = styled.div`
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  ${({ layout }) => layout === 'center' && 'align-items: center;justify-content: center;'}
`

const CardThick = styled.div`
  background-color: ${({ borderColor }) => borderColor || '#000000'};
  background-image: -webkit-linear-gradient(hsla(0, 0%, 100%, 0.25), hsla(0, 0%, 0%, 0.25));
  bottom: 0;
  content: '';
  left: 130px;
  position: absolute;
  top: 0px;
  width: 5px;
  z-index: -10;
  transform: rotateY(-90deg);
  transform-origin: 100% 50%;
`

const Image = styled.img`
  width: 140px;
  height: 91.53px;
  margin: 5px;
`
const Logo = styled.img`
  width: 140px;
  filter: brightness(150%);
`

const Title = styled.p`
  color: #ffffff;
  ${({ layout }) => layout === 'left' && 'display:flex;justify-content: flex-end;padding-right: 20px;'}
  background: linear-gradient(#262626, #eaeaea, #262626);
  -webkit-background-clip: text;
  color: transparent;
`
export const GradientTitle = styled.h1`
  > span {
    /*color:white;*/
    top: 35%;
    left: 0;
    position: absolute;
    transition: translateY(-50%);
    margin: 0;
    padding: 0;
    width: 100%;
    text-align: center;
    font-size: 15px;
    text-transform: uppercase;
    letter-spacing: 5px;
    background: linear-gradient(#262626, #eaeaea, #262626);
    -webkit-background-clip: text;
    color: transparent;
  }
  > span:nth-child(1) {
    z-index: 2;
  }
  > span:nth-child(2) {
    z-index: 1;
    text-shadow: 1px 1px 0 #262626, 2px 2px 0 #262626, 3px 3px 0 #262626, 4px 4px 0 #262626, 5px 5px 0 #262626,
      1px 1px 0 #262626, 6px 20px 20px rgba(0, 0, 0, 1), -1px -1px 0 #fff;
  }
`

// const texture = (rotate) => keyframes`
// // from,
// // to {
// //   transform: translate3d(0, 0, 0) rotateY(${rotate}deg);
// // }
// // 50% {
// //   transform: translate3d(-50%, 0, 0) rotateY(${rotate}deg);

// // }
// `

// const CardTexture = styled.div`
//   animation-name: ${({ rotate }) => texture(rotate)};
//   top: 0;
//   left: 0;
//   width: 100%;
//   height: 100%;
//   animation-duration: 3s;
//   animation-timing-function: ease-in-out;
//   animation-iteration-count: infinite;
//   position: absolute;
//   overflow: hidden;

//   background-image: linear-gradient(-80deg, hsla(0, 0%, 100%, 0.3) 25%, hsla(0, 0%, 100%, 0) 100%);
// `

export default function Home() {
  const [rotate, setRotate] = useState(0)
  const [rotateContent, setRotateContent] = useState(0)
  const [cardBorder, setCardBorder] = useState()
  const [layout, setLayout] = useState('center')
  return (
    <>
      <Flex width="100%" justifyContent="center" alignItems="center" marginTop="30px">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container rotate={rotate}>
          <Content rotateContent={rotateContent} borderColor={cardBorder}>
            <FrontWrapper>
              <Context layout={layout}>
                <Logo src="/img/Your LOGO.png" alt="Your LOGO" />
                <Title layout={layout}>Zahra Namazi</Title>
                <Title layout={layout}>Frontend Developer</Title>
              </Context>
            </FrontWrapper>
            <CardThick borderColor={cardBorder} />
            <BackWrapper>
              <Context layout="center">
                <GradientTitle>
                  <span>CodeSnail</span>
                  <span>CodeSnail</span>
                </GradientTitle>
              </Context>
            </BackWrapper>
          </Content>
          {/* <CardTexture rotate={rotate} /> */}
        </Container>

        <Flex flexDirection="column" marginLeft="30px">
          <Image
            alt="front"
            src="/img/front.svg"
            onClick={() => {
              setRotateContent(0)
              setRotate(0)
            }}
          />
          <Image
            alt="back"
            src="/img/back.svg"
            onClick={() => {
              setRotateContent(180)
              setRotate(0)
            }}
          />
          <Image
            alt="rotate"
            src="/img/rotate.svg"
            onClick={() => {
              setRotateContent(-45)
              setRotate(-45)
            }}
          />
        </Flex>
      </Flex>
      <Flex width="100%" justifyContent={`center`} marginTop="20px">
        <Button
          backgroundColor="#ffd700"
          padding={`10px 20px`}
          onClick={() => {
            setCardBorder('#ffd700')
          }}
        >
          Card Border
        </Button>
        <Button
          backgroundColor="#C0C0C0"
          padding={`10px 20px`}
          onClick={() => {
            setCardBorder('#C0C0C0')
          }}
        >
          Card Border
        </Button>
      </Flex>
      <Flex width="100%" justifyContent={`center`} marginTop="20px">
        <Image src="/img/Logo-name-Tagline.svg" alt="Logo-name-Tagline" onClick={() => setLayout('center')} />
        <Image src="/img/Logo Variant 2.svg" alt="Logo Variant 2" onClick={() => setLayout('left')} />
      </Flex>
    </>
  )
}
