import Head from 'next/head'
import { Button, Flex } from 'rebass'
import { useState } from 'react'

import styled from 'styled-components'

const Container = styled.div`
  background-color: transparent;
  width: 325px;
  height: 204px;
  perspective: 1000px;

  transform: ${({ rotate }) => `rotateY(${rotate}deg)`};
`

const Content = styled.div`
  position: relative;
  // width: 100%;
  // height: 100%;
  text-align: center;
  width: 325px;
  height: 204px;
  perspective: 1000px;
  transform: ${({ rotateContent }) => `rotateY(${rotateContent}deg)`};

  background: transparent url(https://i.imgur.com/GPCt3mC.jpg) no-repeat;
  background-size: 100% 100%;
  border-radius: 5px;
  transition: transform 4s;
  transform-style: preserve-3d;
  :before {
    background-color: ${({ borderColor }) => borderColor || '#000000'};
    position: absolute;
    width: 100%;
    height: 100%;
    border-radius: 5px;
    overflow: hidden;
    z-index: 1;
    content: '';
    top: 0;
    left: 0;
    transform: rotateY(180deg) translateZ(1px);
    background-image: -webkit-linear-gradient(hsla(0, 0%, 100%, 0.25), hsla(0, 0%, 0%, 0.25));
  }
  :after {
    background-color: ${({ borderColor }) => borderColor || '#000000'};
    position: absolute;
    width: 100%;
    height: 100%;
    border-radius: 5px;
    overflow: hidden;
    z-index: 1;
    content: '';
    top: 0;
    left: 0;
    transform: rotateY(180deg) translateZ(5px);
    background-image: -webkit-linear-gradient(hsla(0, 0%, 100%, 0.25), hsla(0, 0%, 0%, 0.25));
  }
`

const Card = styled.div`
  background-color: #000000;
  position: absolute;
  width: 100%;
  height: 100%;
  border-radius: 5px;
  overflow: hidden;
  z-index: 1;
`

const FrontWrapper = styled(Card)`
  background-color: #000000;
  background-image: -webkit-linear-gradient(hsla(0, 0%, 100%, 0.25), hsla(0, 0%, 0%, 0.25));
  color: black;
  opacity: 1;
  transition: opacity 0 0.3s;
`

const BackWrapper = styled(Card)`
  background-color: #000000;
  color: white;
  transform: rotateY(180deg) translateZ(6px);
`

const Context = styled.div`
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  ${({ layout }) => layout === 'center' && 'align-items: center;justify-content: center;'}
`

const CardThick = styled.div`
  background-color: ${({ borderColor }) => borderColor || '#000000'};
  background-image: -webkit-linear-gradient(hsla(0, 0%, 100%, 0.25), hsla(0, 0%, 0%, 0.25));
  bottom: 0;
  content: '';
  left: 130px;
  position: absolute;
  top: 0px;
  width: 5px;
  z-index: -10;
  transform: rotateY(-90deg);
  transform-origin: 100% 50%;
`

const Image = styled.img`
  width: 140px;
  height: 91.53px;
  margin: 5px;
`
const Logo = styled.img`
  width: 140px;
`

const Title = styled.p`
  color: #ffffff;
  ${({ layout }) => layout === 'left' && 'display:flex;justify-content: flex-end;padding-right: 20px;'}
`

export default function Home() {
  const [rotate, setRotate] = useState(0)
  const [rotateContent, setRotateContent] = useState(0)
  const [cardBorder, setCardBorder] = useState()
  const [layout, setLayout] = useState('center')
  return (
    <>
      <Flex width="100%" justifyContent="center" alignItems="center" marginTop="30px">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Container rotate={rotate}>
          <Content rotateContent={rotateContent} borderColor={cardBorder}>
            <FrontWrapper>
              <Context layout={layout}>
                <Logo src="/img/Your LOGO.png" alt="Your LOGO" />
                <Title layout={layout}>Zahra Namazi</Title>
                <Title layout={layout}>Frontend Developer</Title>
              </Context>
            </FrontWrapper>
            <CardThick borderColor={cardBorder} />
            <BackWrapper>
              <Context layout="center">
                <Title>Back</Title>
              </Context>
            </BackWrapper>
          </Content>
        </Container>
        <Flex flexDirection="column" marginLeft="30px">
          <Image
            alt="front"
            src="/img/front.svg"
            onClick={() => {
              setRotateContent(0)
              setRotate(0)
            }}
          />
          <Image
            alt="back"
            src="/img/back.svg"
            onClick={() => {
              setRotateContent(180)
              setRotate(0)
            }}
          />
          <Image
            alt="rotate"
            src="/img/rotate.svg"
            onClick={() => {
              setRotateContent(-45)
              setRotate(-45)
            }}
          />
        </Flex>
      </Flex>
      <Flex width="100%" justifyContent={`center`} marginTop="20px">
        <Button
          backgroundColor="#ffd700"
          padding={`10px 20px`}
          onClick={() => {
            setCardBorder('#ffd700')
          }}
        >
          Card Border
        </Button>
        <Button
          backgroundColor="#C0C0C0"
          padding={`10px 20px`}
          onClick={() => {
            setCardBorder('#C0C0C0')
          }}
        >
          Card Border
        </Button>
      </Flex>
      <Flex width="100%" justifyContent={`center`} marginTop="20px">
        <Image src="/img/Logo-name-Tagline.svg" alt="Logo-name-Tagline" onClick={() => setLayout('center')} />
        <Image src="/img/Logo Variant 2.svg" alt="Logo Variant 2" onClick={() => setLayout('left')} />
      </Flex>
    </>
  )
}
